# -*- coding: utf-8 -*-
"""EV_Market_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXDEekl6v-AGsTNa0hPDWxEVd2Kj-Ey-
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df_yearwise = pd.read_csv('/content/ev_yearwise_total.csv.csv')
df_category = pd.read_csv('/content/ev_categorywise_penetration.csv.csv')
df_buses = pd.read_csv('/content/ev_buses_statewise.csv.csv')

df_yearwise

df_yearwise.info()

df_category.info()

df_buses.info()

df_buses.isnull().sum()

df_buses[df_buses['Strong Hybrid Electric Buses'].notna()][['State/UT', 'Pure Electric Buses', 'Strong Hybrid Electric Buses', 'Total']]

df_buses['Pure Electric Buses'] = df_buses['Pure Electric Buses'].fillna(0)
df_buses['Strong Hybrid Electric Buses'] = df_buses['Strong Hybrid Electric Buses'].fillna(0)

df_buses.isnull().sum()  # should now show all zeros

df_yearwise.info()

df_category.info()

# Step 1: simplify the messy "2023 (Till 01-08-2023)" label to just "2023"
df = df_category.copy()
df.columns = [c.replace('2023 (Till 01-08-2023)', '2023') for c in df.columns]

# Step 2: melt from wide to long
df_long = pd.melt(df, id_vars=['Sl. No.', 'Vehicle Category'], var_name='Year_Metric', value_name='Value')

# Step 3: split "2018 - Total" into separate Year and Metric columns
df_long[['Year', 'Metric']] = df_long['Year_Metric'].str.split(' - ', expand=True)
df_long = df_long.drop(columns=['Year_Metric', 'Sl. No.'])

# Step 4: pivot Metric (Total/EV/%) back into their own columns, one row per category+year
df_category_clean = df_long.pivot_table(
    index=['Vehicle Category', 'Year'],
    columns='Metric',
    values='Value',
    aggfunc='first'
).reset_index()

df_category_clean.columns.name = None
df_category_clean = df_category_clean.rename(columns={
    'Total': 'Total_Vehicles',
    'EV': 'EV_Vehicles',
    '%': 'EV_Percentage'
})

df_category_clean

df_category_clean['EV_Vehicles'] = df_category_clean['EV_Vehicles'].astype(int)
df_category_clean['Total_Vehicles'] = df_category_clean['Total_Vehicles'].astype(int)

df_category_clean

df_category_clean.to_csv('/content/drive/MyDrive/EV_Project/ev_categorywise_clean.csv', index=False)

import sqlite3

# Create (or connect to) a database file
conn = sqlite3.connect('/content/drive/MyDrive/EV_Project/ev_data.db')

# Push all 3 of your dataframes into it as SQL tables
df_yearwise.to_sql('yearwise_total', conn, if_exists='replace', index=False)
df_category_clean.to_sql('categorywise', conn, if_exists='replace', index=False)
df_buses.to_sql('buses_statewise', conn, if_exists='replace', index=False)

print("Tables created successfully")

query = "SELECT * FROM categorywise WHERE Year = '2023' ORDER BY EV_Percentage DESC"
pd.read_sql(query, conn)

query = """
SELECT Year, "Number of Registered Electric Vehicles" AS Total_EVs,
       "Number of Registered Electric Vehicles" - LAG("Number of Registered Electric Vehicles")
       OVER (ORDER BY Year) AS YoY_Change
FROM yearwise_total
ORDER BY Year
"""
pd.read_sql(query, conn)

query = """
SELECT
    c1."Vehicle Category",
    c1.EV_Percentage AS Pct_2018,
    c2.EV_Percentage AS Pct_2023,
    ROUND(c2.EV_Percentage - c1.EV_Percentage, 2) AS Percentage_Point_Growth
FROM categorywise c1
JOIN categorywise c2
    ON c1."Vehicle Category" = c2."Vehicle Category"
WHERE c1.Year = '2018' AND c2.Year = '2023'
ORDER BY Percentage_Point_Growth DESC
"""
pd.read_sql(query, conn)

query = """
SELECT "State/UT", Total
FROM buses_statewise
ORDER BY Total DESC
LIMIT 5
"""
pd.read_sql(query, conn)

query = """
SELECT "State/UT", "Pure Electric Buses", "Strong Hybrid Electric Buses"
FROM buses_statewise
WHERE "Pure Electric Buses" = 0
"""
pd.read_sql(query, conn)

df_buses_clean = df_buses[df_buses['State/UT'] != 'Grand Total'].copy()

# push the cleaned version back into SQL, replacing the old table
df_buses_clean.to_sql('buses_statewise', conn, if_exists='replace', index=False)

print("Grand Total row removed, table updated")

query = """
SELECT "State/UT", Total
FROM buses_statewise
ORDER BY Total DESC
LIMIT 5
"""
pd.read_sql(query, conn)

df_yearwise.to_csv('/content/drive/MyDrive/EV_Project/clean_yearwise.csv', index=False)
df_category_clean.to_csv('/content/drive/MyDrive/EV_Project/clean_categorywise.csv', index=False)
df_buses_clean.to_csv('/content/drive/MyDrive/EV_Project/clean_buses_statewise.csv', index=False)

print("Done")

